/**
 * Represents a single keyword record loaded from Dataverse.
 */
export interface IKeywordRecord {
    /** Primary key of the keyword entity record (GUID). */
    id: string;
    /** Display label shown on the tag. */
    label: string;
    /** Optional hex colour string, e.g. "#E8A202". */
    color?: string;
    /** Optional icon name (Fluent icon) or absolute image URL. */
    icon?: string;
    /** Optional grouping value used to organise the picker list. */
    group?: string;
    /** Optional description shown as a tooltip or subtitle. */
    description?: string;
    /** Optional numeric sort order (lower = earlier). */
    sortOrder?: number;
}

/**
 * Props passed from the PCF control index into the root React component.
 */
export interface IEntityKeywordControlProps {
    /** ComponentFramework context – gives access to WebAPI, mode, etc. */
    context: ComponentFramework.Context<IInputs>;
    /** Callback to signal output changes back to the PCF framework. */
    notifyOutputChanged: () => void;
}

/**
 * Mirrors the properties declared in ControlManifest.Input.xml.
 * The interface is generated by PCF tooling; we duplicate key members
 * here for convenience and type safety.
 */
export interface IInputs {
    relationshipName:        ComponentFramework.PropertyTypes.StringProperty;
    relatedEntityName:       ComponentFramework.PropertyTypes.StringProperty;
    relatedEntitySetName:    ComponentFramework.PropertyTypes.StringProperty;
    navigationPropertyName:  ComponentFramework.PropertyTypes.StringProperty;
    labelFieldName:          ComponentFramework.PropertyTypes.StringProperty;
    colorFieldName:          ComponentFramework.PropertyTypes.StringProperty;
    iconFieldName:           ComponentFramework.PropertyTypes.StringProperty;
    groupFieldName:          ComponentFramework.PropertyTypes.StringProperty;
    descriptionFieldName:    ComponentFramework.PropertyTypes.StringProperty;
    sortOrderFieldName:      ComponentFramework.PropertyTypes.StringProperty;
    allowAssociate:          ComponentFramework.PropertyTypes.TwoOptionsProperty;
    allowDisassociate:       ComponentFramework.PropertyTypes.TwoOptionsProperty;
    allowCreate:             ComponentFramework.PropertyTypes.TwoOptionsProperty;
    searchPlaceholder:       ComponentFramework.PropertyTypes.StringProperty;
    maxVisibleTags:          ComponentFramework.PropertyTypes.WholeNumberProperty;
}

/**
 * Output values the PCF control can write back to the platform.
 * Currently the control is read-only from the platform perspective;
 * all mutations happen via direct WebAPI calls.
 */
export interface IOutputs {
    // reserved for future output bindings
}
